import type { Metadata } from "next";
import { Outfit, JetBrains_Mono } from "next/font/google"; // turbo
import "./globals.css";
import { Navigation } from "@/components/ui/Navigation";
import { Cursor } from "@/components/ui/Cursor";
import { Noise } from "@/components/ui/Noise";
import { cn } from "@/lib/utils";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={cn("min-h-screen bg-background font-sans text-foreground", outfit.variable, jetbrainsMono.variable)}>
        <Cursor />
        <Noise />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
